In [1]:
import pandas as pd
import datasets
from datasets import Image as Image_ds # change name because of similar PIL module
from datasets import Dataset
import os
import requests 
from PIL import Image
from tqdm import tqdm
import torch
from datasets import load_dataset
import numpy as np
import mteb

/Users/au672746/Library/CloudStorage/OneDrive-Aarhusuniversitet/CHC/art-multimodal-benchmark/env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# load dataset from HuggingFace
ds = load_dataset("louisebrix/smk_canon_paintings", split="train")
subset = ds.select(range(30))

In [3]:
from functools import partial

In [6]:
# load dataset from the hub
hf_data = datasets.load_dataset('huggan/wikiart', split='train', streaming=True)
wiki_subset = hf_data.take(200)

# convert dataset to iterable generator
def gen_from_iterable_dataset(iterable_ds):
    yield from iterable_ds

# convert to dataset to be saved locally
ds = datasets.Dataset.from_generator(partial(gen_from_iterable_dataset, wiki_subset), features=wiki_subset.features)

Generating train split: 200 examples [00:19, 10.38 examples/s]

In [7]:
ds.save_to_disk(os.path.join('data', f"wiki_subset"))

Saving the dataset (1/1 shards): 100%|██████████| 200/200 [00:00<00:00, 3749.47 examples/s]

In [3]:
leaderboard = pd.read_csv(os.path.join('data', 'mieb_leaderboard.csv'))

In [12]:
ds[1:20]['period']

['1870',
 '1800',
 '1800',
 '1844',
 '1750',
 '1834',
 '1865',
 '1846',
 '1753',
 '1753',
 '1838',
 '1826',
 '1798-1801',
 '1847',
 '1820-1834',
 '1841-1843',
 '1844',
 '1843',
 '1837']

In [10]:
ds.features.keys()

dict_keys(['smk_id', 'period', 'start_year', 'title', 'first_artist', 'all_artists', 'num_artists', 'main_type', 'all_types', 'image_thumbnail', 'gender', 'birth_death', 'nationality', 'history', 'artist_roles', 'creator_roles', 'num_creators', 'techniques', 'enrichment_url', 'content_person', 'has_text', 'colors', 'geo_location', 'entropy', 'tags_en', 'image', 'rgb', 'embedding', 'grey_embedding', 'grey_image', 'exhibitions', 'acquisition_date', 'responsible_department', 'documentation', 'on_display', 'current_location_name', 'literary_reference', 'object_history_note', 'exhibition_venues', 'smk_exhibitions', 'ex_years', 'exb_canon', 'prod_diff', 'prod_notes', 'prod_year'])

In [10]:
leaderboard['Model'].iloc[10]

'[CLIP-ViT-L-14-laion2B-s32B-b82K](https://huggingface.co/laion/CLIP-ViT-L-14-laion2B-s32B-b82K)'

In [11]:
# get list of all model metas
metas = mteb.get_model_metas()

# filter out image models, save their names
vision_names = [meta.name for meta in metas if "image" in meta.modalities]

To match the model metas with leaderboard positions, we need to find the full model paths of the leaderboard models:

In [12]:
# get model names from column of names + HF links
leaderboard_model_names = []

for model_link in leaderboard['Model'].iloc[0:20]:
    model_name = model_link.split(']')[0][1:]
    leaderboard_model_names.append(model_name)

# match model name to full HF path
models_full_paths = []

for model in leaderboard_model_names:
    for path in vision_names:
        if path.endswith(model):
            models_full_paths.append(path)

model_metas = []
for model in models_full_paths:
    model_meta = mteb.get_model_meta(model)
    model_metas.append(dict(model_meta))

model_metadata = pd.DataFrame(model_metas)

In [13]:
model_metadata.head()

,name,revision,release_date,languages,loader,n_parameters,memory_usage_mb,max_tokens,embed_dim,license,...,public_training_data,framework,reference,similarity_fn_name,use_instructions,training_datasets,adapted_from,superseded_by,is_cross_encoder,modalities
0,QuanSun/EVA02-CLIP-bigE-14-plus,11afd202f2ae80869d6cef18b1ec775e79bd8d12,2023-04-26,[eng-Latn],functools.partial(<function evaclip_loader at ...,5000000000,19073.0,77.0,1024,mit,...,https://laion.ai/blog/laion-5b/,[PyTorch],https://huggingface.co/QuanSun/EVA-CLIP,None,False,{},None,None,None,"[image, text]"
1,laion/CLIP-ViT-bigG-14-laion2B-39B-b160k,bc7788f151930d91b58474715fdce5524ad9a189,2023-01-23,[eng-Latn],functools.partial(<function openclip_loader at...,2540000000,9689.0,77.0,1280,mit,...,https://laion.ai/blog/laion-5b/,[PyTorch],https://huggingface.co/laion/CLIP-ViT-bigG-14-...,None,False,{},None,None,None,"[image, text]"
2,QuanSun/EVA02-CLIP-bigE-14,11afd202f2ae80869d6cef18b1ec775e79bd8d12,2023-04-26,[eng-Latn],functools.partial(<function evaclip_loader at ...,4700000000,17929.0,77.0,1024,mit,...,https://laion.ai/blog/laion-5b/,[PyTorch],https://huggingface.co/QuanSun/EVA-CLIP,None,False,{},None,None,None,"[image, text]"
3,google/siglip-so400m-patch14-384,9fdffc58afc957d1a03a25b10dba0329ab15c2a3,2024-01-08,[eng-Latn],functools.partial(<class 'mteb.models.siglip_m...,878000000,3349.0,64.0,1152,apache-2.0,...,None,[PyTorch],https://huggingface.co/google/siglip-so400m-pa...,None,False,{},None,None,None,"[image, text]"
4,google/siglip-large-patch16-384,ce005573a40965dfd21fd937fbdeeebf2439fc35,2024-01-08,[eng-Latn],functools.partial(<class 'mteb.models.siglip_m...,652000000,2489.0,64.0,1024,apache-2.0,...,None,[PyTorch],https://huggingface.co/google/siglip-large-pat...,None,False,{},None,None,None,"[image, text]"

In [14]:
model_metadata.to_csv('testy.csv')

In [23]:
small_subset = ds.select(range(6))

In [24]:
def extract_embeddings(images, model_path):
    
    meta = mteb.get_model_meta(model_path)
    
    model = meta.load_model()
    
    embeddings = model.get_image_embeddings(images)
    
    return embeddings

In [11]:
from open_clip import create_model_and_transforms

In [36]:
leaderboard['Embedding Dimensions']

0     1024
1     1280
2     1024
3     1152
4     1024
5     1024
6     1024
7      768
8     1024
9      768
10     768
11     768
12     512
13     768
14     768
15    1536
16     768
17     768
18    1024
19     768
20     768
21    4096
22     512
23     768
24     512
25    1024
26     512
27     384
28     768
29     768
30     768
31    3072
32     768
33    1024
34    3072
35     768
36     768
37     768
38     512
39     768
40     512
41     768
42     768
43    1024
44     768
45     768
46    1152
47    1152
Name: Embedding Dimensions, dtype: int64

In [38]:
leaderboard

,Unnamed: 0,Rank (Borda),Model,Zero-shot,Memory Usage (MB),Number of Parameters,Embedding Dimensions,Max Tokens,Mean (Task),Mean (TaskType),Any Any Retrieval,Image Classification,Image Clustering,Visual ST eng,Visual ST multi
0,0,1,[EVA02-CLIP-bigE-14-plus](https://huggingface....,100%,19073,5B,1024,77,77.51,70.23,68.30,85.95,92.38,70.49,34.04
1,1,2,[CLIP-ViT-bigG-14-laion2B-39B-b160k](https://h...,100%,9689,2B,1280,77,75.42,69.07,66.57,83.64,85.59,70.01,39.52
2,2,3,[EVA02-CLIP-bigE-14](https://huggingface.co/Qu...,100%,17929,4B,1024,77,75.95,68.50,67.32,84.51,89.42,67.56,33.71
3,3,4,[siglip-so400m-patch14-384](https://huggingfac...,100%,3349,878M,1152,64,75.60,69.32,67.08,84.58,82.11,67.02,45.82
4,4,5,[siglip-large-patch16-384](https://huggingface...,100%,2489,652M,1024,64,74.97,68.64,66.86,83.70,79.94,68.08,44.62
5,5,6,[CLIP-ViT-g-14-laion2B-s34B-b88K](https://hugg...,100%,5215,1B,1024,77,74.00,67.05,65.23,82.77,82.74,68.00,36.54
6,6,7,[siglip-large-patch16-256](https://huggingface...,100%,2488,652M,1024,64,73.91,67.76,65.40,82.46,82.13,66.06,42.76
7,7,8,[CLIP-ViT-L-14-DataComp.XL-s13B-b90K](https://...,100%,1633,428M,768,77,74.27,68.66,65.18,81.96,86.44,69.02,40.69
8,8,9,[CLIP-ViT-H-14-laion2B-s32B-b79K](https://hugg...,100%,3762,986M,1024,77,73.64,66.89,64.98,82.48,83.86,64.57,38.55
9,9,10,[siglip-base-patch16-512](https://huggingface....,100%,777,204M,768,64,72.57,66.10,65.70,80.89,74.65,66.31,42.97
10,10,11,[CLIP-ViT-L-14-laion2B-s32B-b82K](https://hugg...,100%,1631,428M,768,77,72.44,65.00,63.79,81.24,83.50,65.08,31.41
11,11,12,[siglip-base-patch16-384](https://huggingface....,100%,776,203M,768,64,72.25,65.98,64.75,80.60,76.27,65.96,42.31
12,12,13,[CLIP-ViT-B-16-DataComp.XL-s13B-b90K](https://...,100%,572,150M,512,77,71.05,64.80,62.70,78.60,81.73,67.15,33.82
13,13,14,[siglip-base-patch16-256](https://huggingface....,100%,775,203M,768,64,71.20,64.64,63.63,79.68,75.24,65.35,39.31
14,14,15,[siglip-base-patch16-224](https://huggingface....,100%,775,203M,768,64,70.76,63.82,63.73,79.33,74.50,63.49,38.07
15,15,16,[dinov2-giant](https://huggingface.co/facebook...,100%,4335,1B,1536,Unknown,65.55,51.08,64.92,78.89,81.44,11.73,18.44
16,16,17,[siglip-base-patch16-256-multilingual](https:/...,100%,1414,371M,768,64,70.44,64.94,62.08,78.93,74.56,64.28,44.85
17,17,18,[clip-vit-large-patch14](https://huggingface.c...,⚠️ NA,1631,428M,768,77,70.39,64.21,60.27,80.13,76.41,63.83,40.42
18,18,19,[dinov2-large](https://huggingface.co/facebook...,100%,1161,304M,1024,Unknown,64.81,51.01,63.74,77.99,83.10,9.35,20.88
19,19,20,[EVA02-CLIP-L-14](https://huggingface.co/QuanS...,100%,1633,428M,768,77,66.36,61.85,63.01,68.15,88.27,62.14,27.66
20,20,21,[dinov2-base](https://huggingface.co/facebook/...,100%,330,86M,768,Unknown,63.87,50.75,61.86,76.62,82.74,12.42,20.11
21,21,22,[e5-v](https://huggingface.co/royokong/e5-v),100%,15936,8B,4096,8192,66.60,65.22,52.11,74.49,70.05,77.98,51.50
22,22,23,[CLIP-ViT-B-32-DataComp.XL-s13B-b90K](https://...,100%,576,151M,512,77,67.03,59.08,60.12,75.81,77.37,54.64,27.48
23,23,24,[blip-itm-large-coco](https://huggingface.co/S...,100%,1793,470M,768,512,65.60,61.40,59.14,70.77,77.53,61.19,38.39
24,24,25,[CLIP-ViT-B-32-laion2B-s34B-b79K](https://hugg...,100%,577,151M,512,77,67.32,60.36,59.48,75.64,77.99,58.31,30.40
25,25,26,[voyage-multimodal-3](https://huggingface.co/v...,100%,Unknown,Unknown,1024,32768,NaN,NaN,NaN,71.31,82.41,80.13,73.15
26,26,27,[clip-vit-base-patch16](https://huggingface.co...,⚠️ NA,576,151M,512,77,66.15,60.31,56.49,74.98,69.47,65.26,35.37
27,27,28,[dinov2-small](https://huggingface.co/facebook...,100%,84,22M,384,Unknown,60.97,48.04,59.23,73.56,80.20,8.48,18.74
28,28,29,[blip2-opt-2.7b](https://huggingface.co/Salesf...,100%,14285,3B,768,Unknown,61.28,53.00,51.34,72.95,74.01,41.42,25.30
29,29,30,[bge-visualized-base](https://huggingface.co/B...,100%,1631,196M,768,512,63.65,58.24,55.35,70.40,76.19,60.18,29.11
30,30,31,[blip-itm-large-flickr](https://huggingface.co...,100%,1793,470M,768,512,64.12,59.46,58.08,69.36,76.43,58.49,34.92
31,31,32,[VLM2Vec-LoRA](https://huggingface.co/TIGER-La...,100%,Unknown,Unknown,3072,131072,60.14,60.86,51.57,61.97,72.64,70.19,47.97
32,32,33,[blip-itm-base-coco](https://huggingface.co/Sa...,100%,942,247M,768,512,63.27,60.56,57.32,67.20,70.59,64.53,43.17
33,33,34,[bge-visualized-m3](https://huggingface.co/BAA...,100%,4263,872M,1024,8192,62.23,57.50,56.52,66.54,73.57,62.69,28.17
34,34,35,[VLM2Vec-Full](https://huggingface.co/TIGER-La...,100%,7909,4B,3072,131072,59.91,60.46,51.46,61.97,70.72,70.20,47.97
35,35,36,[jina-clip-v1](https://huggingface.co/jinaai/j...,100%,849,223M,768,8192,63.09,59.08,55.87,68.95,69.95,61.84,38.78
36,36,37,[blip2-opt-6.7b-coco](https://huggingface.co/S...,100%,29577,7B,768,Unknown,60.36,52.02,48.09,73.89,67.84,43.64,26.65
37,37,38,[align-base](https://huggingface.co/kakaobrain...,100%,671,176M,768,64,62.72,55.97,56.11,71.19,59.59,60.45,32.51
38,38,39,[EVA02-CLIP-B-16](https://huggingface.co/QuanS...,100%,568,149M,512,77,57.22,53.22,59.65,55.94,82.55,43.21,24.75
39,39,40,[nomic-embed-vision-v1.5](https://huggingface....,100%,355,92M,768,2048,59.72,50.32,57.92,66.72,83.64,28.28,15.02
40,40,41,[clip-vit-base-patch32](https://huggingface.co...,⚠️ NA,576,151M,512,77,61.76,54.21,53.86,71.12,67.90,52.52,25.66
41,41,42,[blip-itm-base-flickr](https://huggingface.co/...,100%,942,247M,768,512,61.27,58.60,56.28,64.80,67.27,62.17,42.46
42,42,43,[blip-image-captioning-large](https://huggingf...,100%,1792,470M,768,512,60.15,57.34,49.54,66.36,73.70,60.53,36.61
43,43,44,[moco-v3-vit-l](https://github.com/facebookres...,100%,1161,304M,1024,Unknown,NaN,NaN,NaN,62.73,71.70,11.63,18.63
44,44,45,[moco-v3-vit-b](https://github.com/facebookres...,100%,330,86M,768,Unknown,51.31,42.34,46.79,61.31,73.86,11.63,18.09
45,45,46,[blip-image-captioning-base](https://huggingfa...,100%,942,247M,768,512,53.12,50.82,44.72,58.25,63.09,53.12,34.90
46,46,47,[siglip-so400m-patch16-256-i18n](https://huggi...,100%,4306,1B,1152,64,NaN,NaN,NaN,NaN,NaN,NaN,48.36
47,47,48,[siglip-so400m-patch14-224](https://huggingfac...,100%,3347,877M,1152,16,NaN,NaN,NaN,NaN,NaN,NaN,42.63

In [ ]:
# test every model on 1 image to get not-installed dependecies..
for model_path in model_metadata['name']:
    try:
        embedding = extract_embeddings(small_subset[0]['image'], model_path)
        print(f"{model_path}: {embedding.shape}")
    except Exception as e:
        print(f'could not load model {model_path}: {e}')

could not load model QuanSun/EVA02-CLIP-bigE-14-plus: Please run `git clone git@github.com:baaivision/EVA.git`,`pip install ninja timm``pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers``git clone https://github.com/NVIDIA/apex && cd apex && pip install -v --disable-pip-version-check --no-build-isolation --no-cache-dir ./`

/Users/au672746/Library/CloudStorage/OneDrive-Aarhusuniversitet/CHC/art-multimodal-benchmark/env/lib/python3.11/site-packages/mteb/models/openclip_models.py:97: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.no_grad(), torch.cuda.amp.autocast():
/Users/au672746/Library/CloudStorage/OneDrive-Aarhusuniversitet/CHC/art-multimodal-benchmark/env/lib/python3.11/site-packages/torch/amp/autocast_mode.py:266: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
100%|██████████| 1/1 [00:11<00:00, 11.15s/it]

laion/CLIP-ViT-bigG-14-laion2B-39B-b160k: torch.Size([1, 1280])
could not load model QuanSun/EVA02-CLIP-bigE-14: Please run `git clone git@github.com:baaivision/EVA.git`,`pip install ninja timm``pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers``git clone https://github.com/NVIDIA/apex && cd apex && pip install -v --disable-pip-version-check --no-build-isolation --no-cache-dir ./`

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
100%|██████████| 1/1 [00:04<00:00,  4.12s/it]

google/siglip-so400m-patch14-384: torch.Size([1, 1152])

100%|██████████| 1/1 [00:03<00:00,  3.02s/it]

google/siglip-large-patch16-384: torch.Size([1, 1024])

100%|██████████| 1/1 [00:01<00:00,  1.03s/it]

laion/CLIP-ViT-g-14-laion2B-s34B-b88K: torch.Size([1, 1024])

100%|██████████| 1/1 [00:02<00:00,  2.63s/it]

google/siglip-large-patch16-256: torch.Size([1, 1024])

100%|██████████| 1/1 [00:00<00:00,  3.52it/s]

laion/CLIP-ViT-L-14-DataComp.XL-s13B-b90K: torch.Size([1, 768])

100%|██████████| 1/1 [00:00<00:00,  1.78it/s]

laion/CLIP-ViT-H-14-laion2B-s32B-b79K: torch.Size([1, 1024])

100%|██████████| 1/1 [00:00<00:00,  1.09it/s]

google/siglip-base-patch16-512: torch.Size([1, 768])

100%|██████████| 1/1 [00:00<00:00,  4.21it/s]

laion/CLIP-ViT-L-14-laion2B-s32B-b82K: torch.Size([1, 768])

100%|██████████| 1/1 [00:00<00:00,  1.27it/s]

google/siglip-base-patch16-384: torch.Size([1, 768])

100%|██████████| 1/1 [00:00<00:00, 14.19it/s]

laion/CLIP-ViT-B-16-DataComp.XL-s13B-b90K: torch.Size([1, 512])

100%|██████████| 1/1 [00:00<00:00,  1.46it/s]

google/siglip-base-patch16-256: torch.Size([1, 768])

100%|██████████| 1/1 [00:00<00:00,  1.49it/s]

google/siglip-base-patch16-224: torch.Size([1, 768])

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
100%|██████████| 1/1 [00:08<00:00,  8.96s/it]

facebook/dinov2-giant: torch.Size([1, 1536])

100%|██████████| 1/1 [00:00<00:00,  1.21it/s]

google/siglip-base-patch16-256-multilingual: torch.Size([1, 768])

100%|██████████| 1/1 [00:02<00:00,  2.68s/it]

openai/clip-vit-large-patch14: torch.Size([1, 768])

100%|██████████| 1/1 [00:02<00:00,  2.69s/it]

facebook/dinov2-large: torch.Size([1, 1024])
could not load model QuanSun/EVA02-CLIP-L-14: Please run `git clone git@github.com:baaivision/EVA.git`,`pip install ninja timm``pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers``git clone https://github.com/NVIDIA/apex && cd apex && pip install -v --disable-pip-version-check --no-build-isolation --no-cache-dir ./`

In [5]:
import pyarrow as pa
import pyarrow.parquet as pq
import numpy as np

In [7]:
table = pa.Table.from_pydict({'embedding': ds['embedding']})

In [9]:
pq.write_table(table, 'tester')

In [ ]:
import torch
from torch import nn 

# make sure code can run on both GPU and CPU

device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
def fit_and_predict(train_data, 
                    val_data, 
                    test_data, 
                    hidden_layer_size, 
                    embedding_col,
                    label_col, # label
                    batch_size,
                    epochs):

    # use GPU if available, otherwise CPU
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Code is running on {device}")

    # handle this differently ????? 
    num_classes = train_data.features[label_col].num_classes

    # make sure tensor will give the correct output with this
    input_size = len(train_data[0][embedding_col])

    # build torch neural network and send to available device (either CPU (default) or GPU if available)
    model = build_classification_model(input_size, hidden_layer_size, num_classes).to(device)

In [25]:
embeddings_test = extract_embeddings(small_subset['image'], 'openai/clip-vit-base-patch32')

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
100%|██████████| 1/1 [00:00<00:00,  4.40it/s]

In [26]:
embeddings_test.shape

torch.Size([6, 512])

In [30]:
embeddings_np = embeddings_test.cpu().numpy()

embeddings_list = [emb for emb in embeddings_np]  # list of 1D numpy arrays, length=number of rows

small_subset = small_subset.add_column('testy', embeddings_list)

In [33]:
type(small_subset[0]['testy'])

list

In [88]:
model_meta = pd.DataFrame([dict(mteb.get_model_meta(models_full_paths[0]))])
#testy = pd.DataFrame([model_meta])

In [89]:
model_meta

,name,revision,release_date,languages,loader,n_parameters,memory_usage_mb,max_tokens,embed_dim,license,...,public_training_data,framework,reference,similarity_fn_name,use_instructions,training_datasets,adapted_from,superseded_by,is_cross_encoder,modalities
0,QuanSun/EVA02-CLIP-bigE-14-plus,11afd202f2ae80869d6cef18b1ec775e79bd8d12,2023-04-26,[eng-Latn],functools.partial(<function evaclip_loader at ...,5000000000,19073.0,77.0,1024,mit,...,https://laion.ai/blog/laion-5b/,[PyTorch],https://huggingface.co/QuanSun/EVA-CLIP,None,False,{},None,None,None,"[image, text]"

In [85]:
testy.columns

Index(['name', 'revision', 'release_date', 'languages', 'loader',
       'n_parameters', 'memory_usage_mb', 'max_tokens', 'embed_dim', 'license',
       'open_weights', 'public_training_code', 'public_training_data',
       'framework', 'reference', 'similarity_fn_name', 'use_instructions',
       'training_datasets', 'adapted_from', 'superseded_by',
       'is_cross_encoder', 'modalities'],
      dtype='object')

In [86]:
testy

,name,revision,release_date,languages,loader,n_parameters,memory_usage_mb,max_tokens,embed_dim,license,...,public_training_data,framework,reference,similarity_fn_name,use_instructions,training_datasets,adapted_from,superseded_by,is_cross_encoder,modalities
0,QuanSun/EVA02-CLIP-bigE-14-plus,11afd202f2ae80869d6cef18b1ec775e79bd8d12,2023-04-26,[eng-Latn],functools.partial(<function evaclip_loader at ...,5000000000,19073.0,77.0,1024,mit,...,https://laion.ai/blog/laion-5b/,[PyTorch],https://huggingface.co/QuanSun/EVA-CLIP,None,False,{},None,None,None,"[image, text]"

In [81]:
mteb.get_model_metas(models_full_paths)

[ModelMeta(name='openai/clip-vit-large-patch14', revision='32bd64288804d66eefd0ccbe215aa642df71cc41', release_date='2021-02-26', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.clip_models.CLIPModelWrapper'>, model_name='openai/clip-vit-large-patch14'), n_parameters=428000000, memory_usage_mb=1631.0, max_tokens=77.0, embed_dim=768, license=None, open_weights=True, public_training_code=None, public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/openai/clip-vit-large-patch14', similarity_fn_name=None, use_instructions=False, training_datasets=None, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='facebook/dinov2-large', revision='47b73eefe95e8d44ec3623f8890bd894b6ea2d6c', release_date='2023-07-18', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.dino_models.DINOModelWrapper'>, model_name='facebook/dinov2-large'), n_parameters=304000000, memory_usage_mb=1161.0, max_tokens=None, embed_dim=1024, license='apache-2.0', open_weights=True, public_training_code='https://github.com/facebookresearch/dinov2', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/facebook/dinov2-large', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image']),
 ModelMeta(name='facebook/dinov2-giant', revision='611a9d42f2335e0f921f1e313ad3c1b7178d206d', release_date='2023-07-18', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.dino_models.DINOModelWrapper'>, model_name='facebook/dinov2-giant'), n_parameters=1140000000, memory_usage_mb=4335.0, max_tokens=None, embed_dim=1536, license='apache-2.0', open_weights=True, public_training_code='https://github.com/facebookresearch/dinov2', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/facebook/dinov2-giant', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image']),
 ModelMeta(name='QuanSun/EVA02-CLIP-L-14', revision='11afd202f2ae80869d6cef18b1ec775e79bd8d12', release_date='2023-04-26', languages=['eng-Latn'], loader=functools.partial(<function evaclip_loader at 0x349ec1440>, model_name='EVA02-CLIP-L-14'), n_parameters=428000000, memory_usage_mb=1633.0, max_tokens=77.0, embed_dim=768, license='mit', open_weights=True, public_training_code='https://github.com/baaivision/EVA/tree/master/EVA-CLIP', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/QuanSun/EVA-CLIP', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='QuanSun/EVA02-CLIP-bigE-14', revision='11afd202f2ae80869d6cef18b1ec775e79bd8d12', release_date='2023-04-26', languages=['eng-Latn'], loader=functools.partial(<function evaclip_loader at 0x349ec1440>, model_name='EVA02-CLIP-bigE-14'), n_parameters=4700000000, memory_usage_mb=17929.0, max_tokens=77.0, embed_dim=1024, license='mit', open_weights=True, public_training_code='https://github.com/baaivision/EVA/tree/master/EVA-CLIP', public_training_data='https://laion.ai/blog/laion-5b/', framework=['PyTorch'], reference='https://huggingface.co/QuanSun/EVA-CLIP', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='QuanSun/EVA02-CLIP-bigE-14-plus', revision='11afd202f2ae80869d6cef18b1ec775e79bd8d12', release_date='2023-04-26', languages=['eng-Latn'], loader=functools.partial(<function evaclip_loader at 0x349ec1440>, model_name='EVA02-CLIP-bigE-14-plus'), n_parameters=5000000000, memory_usage_mb=19073.0, max_tokens=77.0, embed_dim=1024, license='mit', open_weights=True, public_training_code='https://github.com/baaivision/EVA/tree/master/EVA-CLIP', public_training_data='https://laion.ai/blog/laion-5b/', framework=['PyTorch'], reference='https://huggingface.co/QuanSun/EVA-CLIP', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='laion/CLIP-ViT-L-14-DataComp.XL-s13B-b90K', revision='84c9828e63dc9a9351d1fe637c346d4c1c4db341', release_date='2023-04-26', languages=['eng-Latn'], loader=functools.partial(<function openclip_loader at 0x349f09da0>, model_name='laion/CLIP-ViT-L-14-DataComp.XL-s13B-b90K'), n_parameters=428000000, memory_usage_mb=1633.0, max_tokens=77.0, embed_dim=768, license='mit', open_weights=True, public_training_code='https://github.com/mlfoundations/open_clip', public_training_data='https://huggingface.co/datasets/mlfoundations/datacomp_1b', framework=['PyTorch'], reference='https://huggingface.co/laion/CLIP-ViT-L-14-DataComp.XL-s13B-b90K', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='laion/CLIP-ViT-B-16-DataComp.XL-s13B-b90K', revision='d110532e8d4ff91c574ee60a342323f28468b287', release_date='2023-04-26', languages=['eng-Latn'], loader=functools.partial(<function openclip_loader at 0x349f09da0>, model_name='laion/CLIP-ViT-B-16-DataComp.XL-s13B-b90K'), n_parameters=150000000, memory_usage_mb=572.0, max_tokens=77.0, embed_dim=512, license='mit', open_weights=True, public_training_code='https://github.com/mlfoundations/open_clip', public_training_data='https://huggingface.co/datasets/mlfoundations/datacomp_1b', framework=['PyTorch'], reference='https://huggingface.co/laion/CLIP-ViT-B-16-DataComp.XL-s13B-b90K', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='laion/CLIP-ViT-bigG-14-laion2B-39B-b160k', revision='bc7788f151930d91b58474715fdce5524ad9a189', release_date='2023-01-23', languages=['eng-Latn'], loader=functools.partial(<function openclip_loader at 0x349f09da0>, model_name='laion/CLIP-ViT-bigG-14-laion2B-39B-b160k'), n_parameters=2540000000, memory_usage_mb=9689.0, max_tokens=77.0, embed_dim=1280, license='mit', open_weights=True, public_training_code='https://github.com/mlfoundations/open_clip', public_training_data='https://laion.ai/blog/laion-5b/', framework=['PyTorch'], reference='https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='laion/CLIP-ViT-g-14-laion2B-s34B-b88K', revision='15efd0f6ac0c40c0f9da7becca03c974d7012604', release_date='2023-03-06', languages=['eng-Latn'], loader=functools.partial(<function openclip_loader at 0x349f09da0>, model_name='laion/CLIP-ViT-g-14-laion2B-s34B-b88K'), n_parameters=1367000000, memory_usage_mb=5215.0, max_tokens=77.0, embed_dim=1024, license='mit', open_weights=True, public_training_code='https://github.com/mlfoundations/open_clip', public_training_data='https://laion.ai/blog/laion-5b/', framework=['PyTorch'], reference='https://huggingface.co/laion/CLIP-ViT-g-14-laion2B-s34B-b88K', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='laion/CLIP-ViT-H-14-laion2B-s32B-b79K', revision='de081ac0a0ca8dc9d1533eed1ae884bb8ae1404b', release_date='2022-09-15', languages=['eng-Latn'], loader=functools.partial(<function openclip_loader at 0x349f09da0>, model_name='laion/CLIP-ViT-H-14-laion2B-s32B-b79K'), n_parameters=986000000, memory_usage_mb=3762.0, max_tokens=77.0, embed_dim=1024, license='mit', open_weights=True, public_training_code='https://github.com/mlfoundations/open_clip', public_training_data='https://laion.ai/blog/laion-5b/', framework=['PyTorch'], reference='https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='laion/CLIP-ViT-L-14-laion2B-s32B-b82K', revision='1627032197142fbe2a7cfec626f4ced3ae60d07a', release_date='2022-09-15', languages=['eng-Latn'], loader=functools.partial(<function openclip_loader at 0x349f09da0>, model_name='laion/CLIP-ViT-L-14-laion2B-s32B-b82K'), n_parameters=428000000, memory_usage_mb=1631.0, max_tokens=77.0, embed_dim=768, license='mit', open_weights=True, public_training_code='https://github.com/mlfoundations/open_clip', public_training_data='https://laion.ai/blog/laion-5b/', framework=['PyTorch'], reference='https://huggingface.co/laion/CLIP-ViT-L-14-laion2B-s32B-b82K', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='google/siglip-so400m-patch14-384', revision='9fdffc58afc957d1a03a25b10dba0329ab15c2a3', release_date='2024-01-08', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.siglip_models.SiglipModelWrapper'>, model_name='google/siglip-so400m-patch14-384'), n_parameters=878000000, memory_usage_mb=3349.0, max_tokens=64.0, embed_dim=1152, license='apache-2.0', open_weights=True, public_training_code='https://github.com/google-research/big_vision/blob/main/big_vision/trainers/proj/image_text/siglip.py', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/google/siglip-so400m-patch14-384', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='google/siglip-base-patch16-256-multilingual', revision='8952a4eafcde3cb7ab46b1dd629b33f8784ca9c6', release_date='2024-01-08', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.siglip_models.SiglipModelWrapper'>, model_name='google/siglip-base-patch16-256-multilingual'), n_parameters=371000000, memory_usage_mb=1414.0, max_tokens=64.0, embed_dim=768, license='apache-2.0', open_weights=True, public_training_code='https://github.com/google-research/big_vision/blob/main/big_vision/trainers/proj/image_text/siglip.py', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/google/siglip-base-patch16-256-multilingual', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='google/siglip-base-patch16-256', revision='b078df89e446d623010d890864d4207fe6399f61', release_date='2024-01-08', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.siglip_models.SiglipModelWrapper'>, model_name='google/siglip-base-patch16-256'), n_parameters=203000000, memory_usage_mb=775.0, max_tokens=64.0, embed_dim=768, license='apache-2.0', open_weights=True, public_training_code='https://github.com/google-research/big_vision/blob/main/big_vision/trainers/proj/image_text/siglip.py', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/google/siglip-base-patch16-256', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='google/siglip-base-patch16-512', revision='753a949581523b60257d93e18391e8c27f72eb22', release_date='2024-01-08', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.siglip_models.SiglipModelWrapper'>, model_name='google/siglip-base-patch16-512'), n_parameters=204000000, memory_usage_mb=777.0, max_tokens=64.0, embed_dim=768, license='apache-2.0', open_weights=True, public_training_code='https://github.com/google-research/big_vision/blob/main/big_vision/trainers/proj/image_text/siglip.py', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/google/siglip-base-patch16-512', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='google/siglip-base-patch16-384', revision='41aec1c83b32e0a6fca20ad88ba058aa5b5ea394', release_date='2024-01-08', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.siglip_models.SiglipModelWrapper'>, model_name='google/siglip-base-patch16-384'), n_parameters=203000000, memory_usage_mb=776.0, max_tokens=64.0, embed_dim=768, license='apache-2.0', open_weights=True, public_training_code='https://github.com/google-research/big_vision/blob/main/big_vision/trainers/proj/image_text/siglip.py', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/google/siglip-base-patch16-384', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='google/siglip-base-patch16-224', revision='7fd15f0689c79d79e38b1c2e2e2370a7bf2761ed', release_date='2024-01-08', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.siglip_models.SiglipModelWrapper'>, model_name='google/siglip-base-patch16-224'), n_parameters=203000000, memory_usage_mb=775.0, max_tokens=64.0, embed_dim=768, license='apache-2.0', open_weights=True, public_training_code='https://github.com/google-research/big_vision/blob/main/big_vision/trainers/proj/image_text/siglip.py', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/google/siglip-base-patch16-224', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='google/siglip-large-patch16-256', revision='d0da9f876e7d66b4e250cd2450c3ba2ce735e447', release_date='2024-01-08', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.siglip_models.SiglipModelWrapper'>, model_name='google/siglip-large-patch16-256'), n_parameters=652000000, memory_usage_mb=2488.0, max_tokens=64.0, embed_dim=1024, license='apache-2.0', open_weights=True, public_training_code='https://github.com/google-research/big_vision/blob/main/big_vision/trainers/proj/image_text/siglip.py', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/google/siglip-large-patch16-256', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text']),
 ModelMeta(name='google/siglip-large-patch16-384', revision='ce005573a40965dfd21fd937fbdeeebf2439fc35', release_date='2024-01-08', languages=['eng-Latn'], loader=functools.partial(<class 'mteb.models.siglip_models.SiglipModelWrapper'>, model_name='google/siglip-large-patch16-384'), n_parameters=652000000, memory_usage_mb=2489.0, max_tokens=64.0, embed_dim=1024, license='apache-2.0', open_weights=True, public_training_code='https://github.com/google-research/big_vision/blob/main/big_vision/trainers/proj/image_text/siglip.py', public_training_data=None, framework=['PyTorch'], reference='https://huggingface.co/google/siglip-large-patch16-384', similarity_fn_name=None, use_instructions=False, training_datasets={}, adapted_from=None, superseded_by=None, is_cross_encoder=None, modalities=['image', 'text'])]

In [10]:
import timm

In [11]:
timm.list_models('*eva*')

['eva02_base_patch14_224',
 'eva02_base_patch14_448',
 'eva02_base_patch16_clip_224',
 'eva02_enormous_patch14_clip_224',
 'eva02_large_patch14_224',
 'eva02_large_patch14_448',
 'eva02_large_patch14_clip_224',
 'eva02_large_patch14_clip_336',
 'eva02_small_patch14_224',
 'eva02_small_patch14_336',
 'eva02_tiny_patch14_224',
 'eva02_tiny_patch14_336',
 'eva_giant_patch14_224',
 'eva_giant_patch14_336',
 'eva_giant_patch14_560',
 'eva_giant_patch14_clip_224',
 'eva_large_patch14_196',
 'eva_large_patch14_336']